services:
  app:
    build:
      context: .
    container_name: flask_app
    image: flask-login-app:test
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    command: python app/login.py

  test:
    build:
      context: .
    depends_on:
      - app
    command: >
      sh -c "sleep 5 && pytest -v tests/"
