services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: flask_app
    image: flask-login-app
    ports:
      - "5001:5001"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - app
