name: CI - QA Automation Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: hoverkraft-tech/compose-action@v2
        with:
          compose-file: docker-compose.yml
          up-flags: "--build"

      - name: Wait for test container to finish
        run: |
          echo "Waiting for test container to finish..."
          while docker compose ps test | grep -q "Up"; do sleep 1; done

      - name: Show pytest output
        run: docker compose logs test

      - name: Security Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
            image-ref: flask-login-app:test
            format: 'table'
            exit-code: '0'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
